import { test, expect } from '@playwright/test';

test.describe('Admin Notifications Management', () => {
  test.beforeEach(async ({ page }) => {
    page.on('console', msg => console.log('BROWSER CONSOLE:', msg.text()));
    // Login
    await page.goto('/admin/login');
    await page.fill('input[type="email"]', 'admin@ironfit.com');
    await page.fill('input[type="password"]', 'admin123');
    await page.click('button:has-text("AUTHORIZE ACCESS")');
    await page.waitForURL('**/admin/dashboard');
  });

  test('Send bulk notification', async ({ page }) => {
    await page.goto('/admin/notifications');
    await page.waitForSelector('h1:has-text("Notifications Center")');

    await page.click('button:has-text("Send Notification")');
    await expect(page.locator('h2:has-text("Send Notification")')).toBeVisible();

    const title = `Test Notification ${Date.now()}`;
    await page.fill('input[name="title"]', title);
    await page.fill('textarea[name="message"]', 'This is a test notification generated by Playwright.');
    
    // Select a specific member to avoid bulk SMTP timeout
    await page.selectOption('select[name="userId"]', { index: 1 });
    // Type - System should be default.

    await page.click('button[type="submit"]:has-text("Send Now")');

    // Wait for the form to close which means it succeeded. Bulk notifications might take 10-20 seconds.
    await expect(page.locator('h2:has-text("Send Notification")')).not.toBeVisible({ timeout: 30000 });
    await expect(page.getByText(/Notification sent/i).first()).toBeVisible({ timeout: 15000 });

    // Verify it appears in the list
    await page.fill('input[placeholder*="Search"]', title);
    await expect(page.locator(`h4:has-text("${title}")`).first()).toBeVisible();
  });
});
