import nodemailer from 'nodemailer';
import env from '../config/env.js';
import AutomationLog from '../models/AutomationLog.js';

let transporter = null;

const getTransporter = () => {
  if (transporter) return transporter;
  if (!env.smtpHost || !env.smtpUser || !env.smtpPass || !env.smtpPort || !env.adminEmail) {
    console.warn("[Email] SMTP not configured. Missing required environment variables.");
    return null;
  }
  const cleanHost = env.smtpHost.trim().replace(/^["']|["']$/g, '');
  console.log(`[Email] Connecting to SMTP Host: "${cleanHost}" (Original: "${env.smtpHost}")`);

  transporter = nodemailer.createTransport({
    host: cleanHost,
    port: env.smtpPort,
    secure: env.smtpPort === 465,
    requireTLS: env.smtpPort === 587,
    auth: { user: env.smtpUser, pass: env.smtpPass },
    connectionTimeout: 10000,
    greetingTimeout: 10000,
    socketTimeout: 15000,
  });

  transporter.verify()
    .then(() => console.log('[Email] Transporter verified successfully.'))
    .catch((err) => console.error('[Email] Transporter verification failed:', err.message));
  return transporter;
};

/**
 * Verify SMTP connection by sending a test message to the admin.
 * Returns { success, messageId, error }.
 */
export const verifySmtpConnection = async () => {
  const transport = getTransporter();
  if (!transport) return { success: false, error: 'SMTP not configured' };
  try {
    // Verify transport works by sending a test email to self
    const info = await transport.sendMail({
      from: '"IronFit Elite" <' + env.smtpUser + '>',
      to: env.adminEmail || env.smtpUser,
      subject: 'IronFit Elite — SMTP Test',
      html: '<h1>SMTP Test</h1><p>If you receive this, the SMTP configuration is working.</p>',
    });
    return { success: true, messageId: info.messageId };
  } catch (e) {
    return { success: false, error: e.message };
  }
};

export const sendEmail = async ({ to, subject, html }) => {
  const transport = getTransporter();
  if (!transport) return { success: false, error: 'SMTP not configured' };
  
  // Prevent sending real emails to test data domains generated by E2E tests
  if (to.includes('@example.com') || to.includes('@ironfit.com') || to.includes('@test.com')) {
    console.log(`[Email] Skipped sending to test address: ${to}`);
    return { success: true, messageId: `test-skipped-${Date.now()}` };
  }

  try {
    const info = await transport.sendMail({
      from: '"IronFit Elite" <' + env.smtpUser + '>',
      to, subject, html,
    });
    return { success: true, messageId: info.messageId };
  } catch(e) {
    console.error("[Email] Send failed:", e.message);
    return { success: false, error: e.message };
  }
};

/**
 * Send email and log the result to AutomationLog.
 * Returns the sendEmail result for callers to inspect.
 */
export const sendEmailWithLog = async ({ to, subject, html, category, automation }) => {
  const result = await sendEmail({ to, subject, html });
  try {
    await AutomationLog.create({
      category: category || 'system',
      automation: automation || 'email-send',
      status: result.success ? 'success' : 'error',
      summary: result.success
        ? `Email sent to ${to}: ${subject}`
        : `Email FAILED to ${to}: ${subject} — ${result.error}`,
      details: { to, subject, messageId: result.messageId || null, error: result.error || null },
      recordsAffected: 1,
      duration: 0,
      triggeredAt: new Date(),
    });
  } catch (logErr) {
    console.error('[Email] Log failed:', logErr.message);
  }
  return result;
};

const nl = "\n";

const wrap = (title, content) => {
  return [
    '<!DOCTYPE html><html><head><meta charset="utf-8"></head>',
    '<body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,sans-serif;">',
    '<table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;">',
    '<tr><td style="padding:40px 24px 20px;text-align:center;background:linear-gradient(135deg,#1a1a1a,#0d0d0d);border-bottom:3px solid #ff6200;">',
    '<h1 style="color:#fff;font-size:28px;margin:0;font-weight:800;">IRONFIT <span style="color:#ff6200;">ELITE</span></h1>',
    '<p style="color:#888;font-size:13px;">Premium Fitness Training</p></td></tr>',
    '<tr><td style="padding:32px 24px;background:#111;">',
    '<h2 style="color:#fff;font-size:20px;margin:0 0 16px;">' + title + '</h2>',
    content,
    '</td></tr>',
    '<tr><td style="padding:24px;text-align:center;background:#0a0a0a;">',
    '<p style="color:#555;font-size:12px;margin:0;">IronFit Elite - Bangalore, India</p></td></tr>',
    '</table></body></html>'
  ].join(nl);
};

const row = (l, v) => {
  return '<tr><td style="color:#888;font-size:13px;padding:8px 0;border-bottom:1px solid #1a1a1a;width:120px;">' + l + '</td>'
    + '<td style="color:#fff;font-size:13px;padding:8px 0;border-bottom:1px solid #1a1a1a;">' + v + '</td></tr>';
};

const send = async (to, subject, title, body) => {
  return sendEmailWithLog({ to, subject, html: wrap(title, body) });
};

const body = (parts) => parts.join(nl);

export const sendWelcomeEmail = async (member, temporaryPassword = null) => {
  const passwordSection = temporaryPassword 
    ? `<div style="background:#1a1a1a;border-radius:8px;padding:20px;margin:16px 0;text-align:center;">
         <p style="color:#888;margin:0 0 8px;">Your Temporary Password:</p>
         <h3 style="color:#ff6200;margin:0;letter-spacing:2px;">${temporaryPassword}</h3>
         <p style="color:#888;font-size:12px;margin:12px 0 0;">Please log in and change your password immediately.</p>
       </div>`
    : '';

  return send(member.email, "Welcome to IronFit Elite!",
    "Welcome to IronFit Elite!",
    body([
      '<p style="color:#ccc;font-size:14px;line-height:1.6;">Hi <strong style="color:#fff;">' + member.fullName + '</strong>,</p>',
      '<p style="color:#ccc;font-size:14px;line-height:1.6;">Welcome to IronFit Elite! We are thrilled to have you on board.</p>',
      passwordSection,
      '<table style="margin:20px 0;">',
      row("Name", member.fullName),
      row("Email", member.email),
      row("Phone", member.phone || "---"),
      '</table>',
      '<p style="color:#888;font-size:13px;">See you at the gym!<br><strong style="color:#fff;">Team IronFit Elite</strong></p>'
    ])
  );
};

export const sendLeadNotification = async (lead) => {
  return send(env.adminEmail || env.smtpUser, "New Lead: " + lead.fullName,
    "New Lead Captured",
    body([
      '<table style="margin:16px 0;">',
      row("Name", lead.fullName),
      row("Email", lead.email),
      row("Phone", lead.phone || "---"),
      row("Source", lead.source || "website"),
      '</table>'
    ])
  );
};

export const sendExpiryReminder = async (member, subscription) => {
  const d = Math.ceil((new Date(subscription.endDate) - new Date()) / (1000 * 60 * 60 * 24));
  return send(member.email, "Membership Expiring in " + d + " Days",
    "Membership Expiry Reminder",
    body([
      '<p style="color:#ccc;font-size:14px;">Hi ' + member.fullName + ', your membership expires soon!</p>',
      '<table>',
      row("Plan", subscription.planId?.planName || "Unknown"),
      row("Expires", new Date(subscription.endDate).toLocaleDateString()),
      row("Days Left", String(d)),
      '</table>'
    ])
  );
};

export const sendPaymentReminder = async (member, subscription) => {
  return send(member.email, "Payment Reminder - IronFit Elite",
    "Payment Reminder",
    body([
      '<table>',
      row("Plan", subscription.planId?.planName || "Unknown"),
      row("Amount", "$" + (subscription.planId?.price || 0)),
      '</table>'
    ])
  );
};

export const sendPaymentReceipt = async (member, payment, plan) => {
  return send(member.email, "Receipt - $" + payment.amount.toFixed(2) + " - IronFit Elite",
    "Payment Receipt",
    body([
      '<table>',
      row("Plan", plan?.planName || payment?.planName || "——"),
      row("Amount", "$" + payment.amount.toFixed(2)),
      row("Date", new Date(payment.paymentDate).toLocaleString()),
      row("Method", payment.paymentMethod),
      row("Status", payment.status),
      row("Transaction ID", payment.transactionId || "---"),
      '</table>'
    ])
  );
};

export const sendTrainerAssignment = async (member, trainer) => {
  return send(member.email, "Your Trainer: " + trainer.fullName + " - IronFit Elite",
    "Trainer Assigned",
    body([
      '<p style="color:#ccc;font-size:14px;">Hi ' + member.fullName + ', you have been assigned a trainer!</p>',
      '<div style="background:#1a1a1a;border-radius:8px;padding:20px;margin:16px 0;text-align:center;">',
      '<h3 style="color:#fff;">' + trainer.fullName + '</h3>',
      '<p style="color:#ff6200;">' + (trainer.specialization || "Personal Trainer") + '</p></div>',
      '<table>',
      row("Email", trainer.email),
      row("Phone", trainer.phone || "---"),
      '</table>'
    ])
  );
};

export const sendRenewalConfirmation = async (member, subscription) => {
  const plan = subscription.planId || {};
  return send(member.email, "Membership Renewed - IronFit Elite",
    "Membership Renewed Successfully",
    body([
      '<p style="color:#ccc;font-size:14px;">Hi ' + member.fullName + ', your membership has been renewed!</p>',
      '<table>',
      row("Plan", plan.planName || "Unknown"),
      row("New End Date", new Date(subscription.endDate).toLocaleDateString()),
      row("Status", "Active"),
      '</table>',
      '<p style="color:#888;font-size:13px;">Thank you for being a valued member!<br><strong style="color:#fff;">Team IronFit Elite</strong></p>'
    ])
  );
};

export const sendWorkoutAssignment = async (member, workout) => {
  return send(member.email, "New Workout: " + workout.title + " - IronFit Elite",
    "Workout Assigned",
    body([
      '<p style="color:#ccc;font-size:14px;">Hi ' + member.fullName + ', a new workout has been assigned!</p>',
      '<table>',
      row("Workout", workout.title),
      row("Difficulty", workout.difficulty),
      row("Duration", workout.durationWeeks + " weeks"),
      row("Exercises", (workout.exercises?.length || 0) + " exercises"),
      '</table>'
    ])
  );
};
